version: "3.8"

services:
    redis:
        image: redis:alpine
        volumes:
            - redis:/data
        ports:
            - 12379:6379
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    postgres:
        image: postgres:alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 12432:5432
        environment:
            TZ: UTC
            POSTGRES_DB: laravel
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
    minio:
        image: minio/minio:latest
        ports:
            - "12900:9000"
            - "12901:9001"
        environment:
            - MINIO_ROOT_USER=minio
            - MINIO_ROOT_PASSWORD=minio123
        entrypoint: sh
        command: -c "
            mkdir -p /data/.minio.sys/buckets;
            cp -r /policies/* /data/.minio.sys/;
            cp -r /export/* /data/;
            minio server /data --console-address ":9001";
            "
        volumes:
            - minio:/data
            - ./.docker/minio/export:/export
            - ./.docker/minio/policies:/policies
volumes:
    postgres_data:
        driver: local
    minio:
        driver: local
    redis:
        driver: local
