### Login
POST {{baseUrl}}/auth/login
Content-Type: : application/json
Accept: : application/json
X-Locale: en

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Logout
GET {{baseUrl}}/auth/logout
Accept: application/json
X-Request-Id: 01J172D3CWP97DHYQR8BNZFP5D
Authorization: Bearer {{token}}
content-type: application/json
