### Login
POST {{baseUrl}}/auth/login
content-type: application/json
X-Lang: en

{
    "email": "{{email}}",
    "password": "{{password}}"
}

### Logout
GET {{baseUrl}}/auth/logout
Authorization: Bearer {{token}}
content-type: application/json
